### ISSUE TITLE
Fixing the button position

### ISSUE THREAD

**Issue by chezfo** [cjdduarte/Defer_Cards#2]
The button is lower than the other buttons.

![image](https://user-images.githubusercontent.com/85172877/210447306-d1f22141-b83a-4e5a-8605-81da15bbfb97.png)

The solution: remove in line 123 the `<br>`

change this line
```
 dbtn = """<td width="50" align="right" valign="top" class="stat"><br><button title="Shortcut key: _" id="defbut" onclick="%s(&quot;deferbtn&quot;);">defer</button></td>"""%lnkcmd
```
Replace with this:
```
 dbtn = """<td width="50" align="right" valign="top" class="stat"><button title="Shortcut key: _" id="defbut" onclick="%s(&quot;deferbtn&quot;);">defer</button></td>"""%lnkcmd
```

outcome:

![image](https://user-images.githubusercontent.com/85172877/210448756-6707f03b-7539-401f-8f39-62ed25c319f8.png)

**Comment by cjdduarte** [comment]
resolved. tanks
