### ISSUE TITLE
Moving the button to the right side of the browser.

### ISSUE THREAD

**Issue by chezfo** [cjdduarte/Defer_Cards#3]
I suggest moving the button to the right side of the browser, the reason for my suggestion is because there is already a plugin that adds "skip" to the left side.

https://ankiweb.net/shared/info/1136455830

**Comment by Osiris34** [comment]
I would like to help fix this issue. May you assign it to me?

**Comment by GBS9786** [comment]
Is there a way to defer the entire NOTE and not just the CARD? Thanks!
