### ISSUE TITLE
Anki 23.10.1: Add-on Startup Failed

### ISSUE THREAD

**Issue by SilverBear67** [cjdduarte/Defer_Cards#5]
Hi Carlos,

After having update to Anki 23.10.1  / Qt 5 (Qt 6 has the same issue) on Anki Desktop (Windows 10), I receive the following message from Anki :

**Add-on Startup Failed**
The following add-ons failed to load:

Defer Cards

They may need to be updated to support this version of Anki. Click the Check for Updates button to see if any updates are available.
You can use the Copy Debug Info button to get information that you can paste in a report to the add-on author.
For add-ons that don't have an update available, you can disable or delete the add-on to prevent this message from appearing.

**Debug Information**
Anki 23.10.1 (fac9e0ee) Python 3.9.15 Qt 5.15.2 PyQt 5.15.5
Platform: Windows-10-10.0.19045
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-11-20 23:52:20

When loading Defer Cards:
Traceback (most recent call last):
  File "aqt.addons", line 245, in loadAddons
  File "C:\Users\....\AppData\Roaming\Anki2\addons21\149564514\__init__.py", line 6, in <module>
    from . import defer_cards
  File "C:\Users\....\AppData\Roaming\Anki2\addons21\149564514\defer_cards.py", line 15, in <module>
    import anki.sched
ModuleNotFoundError: No module named 'anki.sched'

If you will find some time to fix this problem, it would be great and I would appreciate it. I'm working with this AddOn on a daily basis and I miss this functionality very much.

Thanks and Regards,
Martin

**Comment by GBS9786** [comment]
Yes, please update this app to be compatible with the latest version of Anki, it is immensely helpful. Thank you!
