### ISSUE TITLE
crash and breakdown the database

### ISSUE THREAD

**Issue by AnkitMayank** [cjdduarte/Defer_Cards#8]
Anki 23.12.1 (1a1d4d54)  (ao)
Python 3.9.15 Qt 6.6.1 PyQt 6.6.1
Platform: Windows-10-10.0.19045

Traceback (most recent call last):
  File "C:\Users\ankit\AppData\Roaming\Anki2\addons21\149564514\defer_cards.py", line 63, in defer
    self.swap(did, card)
  File "C:\Users\ankit\AppData\Roaming\Anki2\addons21\149564514\defer_cards.py", line 84, in swap
    if card.queue == 1 and mw.col.sched.name != "std2":
  File "anki._legacy", line 80, in __getattr__
AttributeError: 'Scheduler' object has no attribute 'name'

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
Advanced Browser ['874215009', 2023-10-21T20:34, 'None', '']
Advanced Copy Fields Qt6 ['287110490', 2023-11-10T23:52, 'None', '']
AnKing Deck Dupe Detector ['1080482686', 2024-09-01T01:25, 'None', '']
AnKing Note Types Easy Customization ['952691989', 2024-08-19T14:41, 'None', mod]
Anki Fantasy ['752559584', 2024-09-27T22:57, 'None', '']
Anki Terminator - ChatGPT Sidebar for Review GoogleGemini Created by Shige ['1428126516', 2024-09-04T06:41, 'None', mod]
AnkiPet - gamify your learning by caring for a pet Fixed by Shige ['2026040256', 2024-06-16T12:21, 'None', mod]
AnkiScape RuneScape Anki ['1808450369', 2024-08-22T21:12, 'None', '']
Audiovisual Feedback ['231569866', 2023-07-09T09:34, '0.8', mod]
Batch Editing ['291119185', 2023-10-26T06:38, 'None', '']
BetterSearch ['1052724801', 2024-03-06T22:25, 'None', '']
Bionic Reading ['649714433', 2023-10-27T03:24, 'None', mod]
Clickable Tags v20 ['1739176371', 2022-01-31T04:58, 'None', '']
Colorful Tags  Hierarchical Tags ['594329229', 2022-09-15T21:06, 'None', '']
Countdown To Events and Exams ['1143540799', 2022-06-27T17:50, 'None', '']
Defer Cards Not to answer them immediately ['149564514', 2024-09-25T21:02, 'None', '']
Edit Field During Review Cloze ['385888438', 2024-01-03T13:19, '6.18', mod]
Extended Tag AddEdit Dialog ['1135507717', 2023-11-11T22:58, 'None', '']
High Yield Tags ['1918380616', 2023-01-11T01:14, 'None', mod]
Hint Hotkeys ['1844908621', 2023-04-14T20:13, 'None', '']
Image Occlusion Enhanced for Anki 21 alpha ['1374772155', 2022-04-09T13:15, 'None', '']
Image Style Editor ['1593969147', 2021-12-17T13:01, 'None', mod]
Leech Toolkit - Advanced leech tag management Fixed by Shige ['1633380637', 2024-02-21T13:33, 'None', '']
More Overview Stats 21 ['738807903', 2024-08-22T15:14, 'None', '']
Motivanki ['663438166', 2022-06-23T21:38, 'None', '']
No Distractions Full Screen Fixed by Shige ['1370336700', 2024-08-26T11:08, 'None', mod]
PDF to notes Fixed by Shige ['1660513597', 2024-04-06T11:24, 'None', mod]
Puppy Reinforcement ['1722658993', 2023-11-16T18:59, 'None', '']
ReColor ['688199788', 2024-03-03T07:45, '3.0', mod]
Review Heatmap ['1771074083', 2022-06-30T07:43, 'None', '']
Show total review count in main screen ['1730200873', 2023-10-14T23:00, 'None', mod]
Special Fields ['1102281552', 2024-03-20T05:34, 'None', mod]
Speed Focus Mode auto-alert auto-reveal auto-answer ['1046608507', 2022-12-16T17:24, 'None', mod]
The KING of Button Add-ons ['374005964', 2024-09-23T18:14, 'None', '']
Web Browser - Search terms Import texts and images automatically ['864545277', 2023-11-18T01:28, 'None', mod]

===IDs of active AnkiWeb add-ons===
1046608507 1052724801 1080482686 1102281552 1135507717 1143540799 1370336700 1374772155 1428126516 149564514 1593969147 1633380637 1660513597 1722658993 1730200873 1739176371 1771074083 1808450369 1844908621 1918380616 2026040256 231569866 287110490 291119185 374005964 385888438 594329229 649714433 663438166 688199788 738807903 752559584 864545277 874215009 952691989

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
'' ['answer-visual-confirmation', 0, 'None', mod]
'' ['popup_dictionary', 0, 'None', '']
AMBOSS add-on ['0amboss_addon', 2022-09-08T18:45, 'None', mod]
Always On Top - permanently keep Anki as top Fixed by Shige ['1045980020', 2024-05-02T07:22, 'None', '']
Anki Habitica for 21 ['1758045507', 2024-09-03T16:47, 'None', mod]
Anki Killstreaks - Reward Medals for Correct Answers Fixed by Shige ['1562475180', 2024-09-20T00:43, 'None', mod]
Anki Leaderboard - Compete with friends to boost motivation Fork by Shige ['175794613', 2024-09-16T00:18, 'None', mod]
Anki Zoom ['538879081', 2020-04-04T06:20, 'v1.1.3', mod]
Anki magnifying glass mouse cursor ['842653376', 2022-12-31T18:44, 'None', '']
AnkiBrain AnkiChatGPT - GPT-4 GPT 35 with auto-cards and document analysis ['1915225457', 2024-09-06T05:58, 'None', '']
AnkiConnect ['2055492159', 2024-07-26T10:55, 'None', '']
AnkiCraft ['368161874', 2024-08-22T15:46, 'None', '']
AnkiHub ['1322529746', 2024-09-30T17:21, 'None', '']
Ankimon by Unlucky-life ['1908235722', 2024-05-16T21:07, 'None', mod]
Ankimote - remote to control Anki from your phone ['149004221', 2021-08-11T22:57, 'None', '']
Ankitty ['1319623242', 2024-07-06T17:26, 'None', '']
Answer visual  auditory  custom text reinforcement ['976516370', 2024-03-08T15:04, 'None', mod]
AwesomeTTS - Add speech to your flashcards ['1436550454', 2024-09-14T12:04, 'None', '']
Break Timer - After 10 cards take a 3 minute break Created by Shige ['174058935', 2024-08-30T14:13, 'None', mod]
Browser MaximizeHide TableEditorSidebar ['1819291495', 2023-06-24T20:09, 'None', '']
Color Confirmation ['1084228676', 2024-01-06T15:55, 'None', '']
Custom Background Image and Gear Icon ['1210908941', 2023-04-19T07:19, 'None', mod]
Customize Keyboard Shortcuts ['24411424', 2023-11-01T15:17, 'None', '']
Enhance main window Customized by Shige ['911023479', 2024-09-25T02:49, 'None', mod]
Exam Notifier ['236593452', 2023-01-19T23:12, 'None', '']
Field AutoComplete ['511710206', 2024-07-20T20:07, 'None', mod]
Google Dictionary ['1346635841', 2022-07-29T03:22, 'None', '']
Highlight Search Results in the Browser ['225180905', 2023-10-22T01:17, 'None', '']
Hitmarkers ['1776869150', 2024-02-24T17:19, 'None', '']
ImageResizer ['1214357311', 2023-12-03T07:58, 'None', '']
Keep model of add cards ['424778276', 2021-10-16T23:36, 'None', '']
Leaderboard ['41708974', 2023-01-15T16:53, 'None', '']
Life Drain ['715575551', 2024-04-30T13:15, 'None', mod]
More Decks Stats and Time Left ['1556734708', 2024-08-20T04:49, 'None', '']
Opening the same window multiple time ['354407385', 2023-11-05T07:59, 'None', '']
Picmonic Anki Add-On ['40737180', 2024-01-24T22:02, 'None', mod]
Play a celebrationcompletion sound when you finish your deck ['978869609', 2024-01-12T10:43, 'None', mod]
Pokemanki Gold - Raising Pokemon with Anki Customized by Shige ['1677779223', 2024-10-02T14:36, 'None', mod]
Progress Graphs and Stats for Learned and Matured Cards ['266436365', 2020-03-29T12:26, 'None', '']
Progress bar - Visualize reviewed cards and remaining Fixed by Shige ['1708250053', 2024-08-14T23:28, 'None', mod]
Remaining time for Anki 21 ['1508357010', 2024-04-16T08:15, '20.12.13i151', mod]
RuneScape-Gamification ['931346754', 2022-12-28T03:06, 'None', '']
Show total time spent in main screen ['1238121460', 2020-07-19T14:36, 'None', '']
Tetris Break for Anki ['1844476877', 2024-02-01T23:56, 'None', mod]
Today Again Count  Created by Shige ['50293437', 2024-08-24T18:47, 'None', mod]
copy note contents to new Add window from Browser Reviewer Add EditCurrent ['759018284', 2022-08-16T16:28, 'None', '']
pasteOCR ['1746010116', 2023-02-27T04:47, 'None', '']

**Comment by cjdduarte** [comment]
I will evaluate the bug and get back to you as soon as possible

**Comment by cjdduarte** [comment]
Fixed compatibility issues with Scheduler attribute in Anki 24.06+

**Comment by AnkitMayank** [comment]
thanks

**Comment by AnkitMayank** [comment]
didn't worked

**Comment by AnkitMayank** [comment]
thanks

**Comment by AnkitMayank** [comment]
after update, it is working
